Fixed installcheck target in gribLoad

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -18,12 +18,10 @@ pkglib_PROGRAMS = 		gribLoad
 # This is to be replaced by a "find wdb" macro:
 AM_CXXFLAGS = 			$(wdb_CFLAGS)
 	
-gribLoad_CPPFLAGS =  	-I$(top_srcdir)/src \
-						-I$(top_srcdir)/test/util/gribWrite \
-						-I$(top_srcdir)/test/util/gribWrite/test
+gribLoad_CPPFLAGS =  	-I$(top_srcdir)/src
 												
 gribLoad_LDADD =		-lwdbLoaderBase -lwdbConfiguration -lwdbProjection \
-						-lwdbException -lwdbLogHandler
+						-lwdbException -lwdbLogHandler -lwdbMath
 
 SED_SUBSTITUTION = 		sed s/__WDB_VERSION__/$(WDB_VERSION)/g $<\
 						| sed s¤__WDB_LIB_PATH__¤"$(LD_LIBRARY_PATH)"¤g \
@@ -32,7 +30,7 @@ SED_SUBSTITUTION = 		sed s/__WDB_VERSION__/$(WDB_VERSION)/g $<\
 						| sed s:__WDB_SRCDIR__:@srcdir@:g \
 			 			| sed s:__WDB_BINDIR__:@bindir@:g \
 			 			| sed s:__WDB_LIBDIR__:@libdir@:g \
-			 			| sed s:__WDB_PKGLIBDIR__:$(libdir)/wdb:g \
+			 			| sed s:__WDB_PKGLIBDIR__:$(libdir)/gribload:g \
 			 			| sed s:__WDB_PKGDATADIR__:$(pkgdatadir):g \
 			 			| sed s:__WDB_DATADIR__:$(wdbdatadir):g \
 			 			| sed s:__WDB_SYSCONFDIR__:@sysconfdir@:g \
@@ -44,8 +42,231 @@ SED_SUBSTITUTION = 		sed s/__WDB_VERSION__/$(WDB_VERSION)/g $<\
 						| sed s:__WCI_LIB__:wci-$(WDB_VERSION).so:g \
 			 			> $@
 
+CRON_COMPILE =			$(SED_SUBSTITUTION);\
+						chmod 754 $@
+
+CSV_COMPILE =			$(SED_SUBSTITUTION)
+
+ENT_COMPILE =			$(SED_SUBSTITUTION)
+
+SH_COMPILE =			$(SED_SUBSTITUTION);\
+						chmod 754 $@
+
+SQL_COMPILE =			$(SED_SUBSTITUTION)
+
+TEST_COMPILE =			$(SED_SUBSTITUTION);\
+						chmod 754 $@
+
+SUFFIXES = 				.in.cron .cron \
+						.in.csv .csv \
+						.in.ent .ent \
+						.in.sh .sh \
+						.in.sql .sql \
+						.in.test .test
+
+# Compile Rules
+.in.cron.cron:
+						$(CRON_COMPILE)
+
+.in.csv.csv:
+						$(CSV_COMPILE)
+
+.in.ent.ent:
+						$(ENT_COMPILE)
+
+.in.sh.sh:
+						$(SH_COMPILE)
+
+.in.sql.sql:
+						$(SQL_COMPILE)
+
+.in.test.test:
+						$(TEST_COMPILE)
+
+noinst_PROGRAMS =
+noinst_SCRIPTS =
 EXTRA_DIST =
+INSTALLTESTS =
+CLEANFILES =
+DISTCLEANFILES =
 
 include src/gribLoad.mk
 include test/install/gribLoad.mk
-include test/util/gribLoad.mk
+include test/util/gribWrite/gribLoad.mk
+
+
+
+#-----------------------------------------------------------------------------
+# Install Check Framework
+#-----------------------------------------------------------------------------
+
+is_local: $(INSTALLCHECK_PROGRAMS)
+	set -e
+	for P in $(INSTALLCHECK_PROGRAMS); do
+		. $(P)
+	done
+
+
+installcheck-local: $(INSTALLTESTS)
+	@failed=0; \
+	all=0; \
+	xfail=0; \
+	xpass=0; \
+	skip=0; \
+	list='$(INSTALLTESTS)'; \
+	if test -n "$$list"; then \
+		for tst in $$list; do \
+			echo " "; \
+			if test -f ./$$tst; then dir=./; \
+	    		elif test -f $$tst; then dir=; \
+	    		else dir="test/install"; \
+			fi; \
+	    		if $(TESTS_ENVIRONMENT) $${dir}$$tst; then \
+	      			all=`expr $$all + 1`; \
+	      			case " $(XFAIL_TESTS) " in \
+				*" $$tst "*) \
+					xpass=`expr $$xpass + 1`; \
+					failed=`expr $$failed + 1`; \
+					echo "XPASS: $$tst"; \
+	      				;; \
+	      			*) \
+					echo "PASS: $$tst"; \
+	      				;; \
+	      			esac; \
+			elif test $$? -ne 77; then \
+	  			all=`expr $$all + 1`; \
+	  			case " $(XFAIL_TESTS) " in \
+				*" $$tst "*) \
+					xfail=`expr $$xfail + 1`; \
+					echo "XFAIL: $$tst"; \
+	      				;; \
+	      			*) \
+					failed=`expr $$failed + 1`; \
+					echo "FAIL: $$tst"; \
+	      				;; \
+	      			esac; \
+	    		else \
+	      			skip=`expr $$skip + 1`; \
+	      			echo "SKIP: $$tst"; \
+	    		fi; \
+	  	done; \
+	  	if test "$$failed" -eq 0; then \
+	    		if test "$$xfail" -eq 0; then \
+	      			banner="All $$all tests passed"; \
+	    		else \
+	      			banner="All $$all tests behaved as expected ($$xfail expected failures)"; \
+	    		fi; \
+	  	else \
+	    		if test "$$xpass" -eq 0; then \
+	      			banner="$$failed of $$all tests failed"; \
+	    		else \
+	      			banner="$$failed of $$all tests did not behave as expected ($$xpass unexpected passes)"; \
+	    		fi; \
+	  	fi; \
+	  	dashes="$$banner"; \
+	  	skipped=""; \
+	  	if test "$$skip" -ne 0; then \
+	    		skipped="($$skip tests were not run)"; \
+	    		test `echo "$$skipped" | wc -c` -le `echo "$$banner" | wc -c` || \
+	      			dashes="$$skipped"; \
+	  	fi; \
+	  	report=""; \
+	  	if test "$$failed" -ne 0 && test -n "$(PACKAGE_BUGREPORT)"; then \
+	    		report="Please report to $(PACKAGE_BUGREPORT)"; \
+	    		test `echo "$$report" | wc -c` -le `echo "$$banner" | wc -c` || \
+	      		dashes="$$report"; \
+	  	fi; \
+	  	dashes=`echo "$$dashes" | sed s/./=/g`; \
+	  	echo "$$dashes"; \
+	  	echo "$$banner"; \
+	  	test -z "$$skipped" || echo "$$skipped"; \
+	  	test -z "$$report" || echo "$$report"; \
+	  	echo "$$dashes"; \
+	  	test "$$failed" -eq 0; \
+	else :; \
+	fi
+
+
+
+#-----------------------------------------------------------------------------
+# Performance Check Framework
+#-----------------------------------------------------------------------------
+
+performancecheck:  $(PERFORMANCETESTS)
+	@failed=0; \
+	all=0; \
+	xfail=0; \
+	xpass=0; \
+	skip=0; \
+	list='$(PERFORMANCETESTS)'; \
+	if test -n "$$list"; then \
+		for tst in $$list; do \
+			echo " "; \
+			if test -f ./$$tst; then dir=./; \
+	    		elif test -f $$tst; then dir=; \
+	    		else dir="test/install"; \
+			fi; \
+	    		if $(TESTS_ENVIRONMENT) $${dir}$$tst; then \
+	      			all=`expr $$all + 1`; \
+	      			case " $(XFAIL_TESTS) " in \
+				*" $$tst "*) \
+					xpass=`expr $$xpass + 1`; \
+					failed=`expr $$failed + 1`; \
+					echo "XPASS: $$tst"; \
+	      				;; \
+	      			*) \
+					echo "PASS: $$tst"; \
+	      				;; \
+	      			esac; \
+			elif test $$? -ne 77; then \
+	  			all=`expr $$all + 1`; \
+	  			case " $(XFAIL_TESTS) " in \
+				*" $$tst "*) \
+					xfail=`expr $$xfail + 1`; \
+					echo "XFAIL: $$tst"; \
+	      				;; \
+	      			*) \
+					failed=`expr $$failed + 1`; \
+					echo "FAIL: $$tst"; \
+	      				;; \
+	      			esac; \
+	    		else \
+	      			skip=`expr $$skip + 1`; \
+	      			echo "SKIP: $$tst"; \
+	    		fi; \
+	  	done; \
+	  	if test "$$failed" -eq 0; then \
+	    		if test "$$xfail" -eq 0; then \
+	      			banner="All $$all tests passed"; \
+	    		else \
+	      			banner="All $$all tests behaved as expected ($$xfail expected failures)"; \
+	    		fi; \
+	  	else \
+	    		if test "$$xpass" -eq 0; then \
+	      			banner="$$failed of $$all tests failed"; \
+	    		else \
+	      			banner="$$failed of $$all tests did not behave as expected ($$xpass unexpected passes)"; \
+	    		fi; \
+	  	fi; \
+	  	dashes="$$banner"; \
+	  	skipped=""; \
+	  	if test "$$skip" -ne 0; then \
+	    		skipped="($$skip tests were not run)"; \
+	    		test `echo "$$skipped" | wc -c` -le `echo "$$banner" | wc -c` || \
+	      			dashes="$$skipped"; \
+	  	fi; \
+	  	report=""; \
+	  	if test "$$failed" -ne 0 && test -n "$(PACKAGE_BUGREPORT)"; then \
+	    		report="Please report to $(PACKAGE_BUGREPORT)"; \
+	    		test `echo "$$report" | wc -c` -le `echo "$$banner" | wc -c` || \
+	      		dashes="$$report"; \
+	  	fi; \
+	  	dashes=`echo "$$dashes" | sed s/./=/g`; \
+	  	echo "$$dashes"; \
+	  	echo "$$banner"; \
+	  	test -z "$$skipped" || echo "$$skipped"; \
+	  	test -z "$$report" || echo "$$report"; \
+	  	echo "$$dashes"; \
+	  	test "$$failed" -eq 0; \
+	else :; \
+	fi
